export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_ERROR = 'SET_USER_ERROR';
export const SET_USER_REQUEST = 'SET_USER_REQUEST';

export const SET_INIT_SLIDE = 'SET_INIT_SLIDE';
export const SET_NEXT_SLIDE = 'SET_NEXT_SLIDE';
export const SET_PREVIOUS_SLIDE = 'SET_PREVIOUS_SLIDE';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';

export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENT_REQUEST = 'GET_COMMENT_REQUEST';

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST';
export const EDIT_COMMENT_FAILURE = 'EDIT_COMMENT_FAILURE';
