export const RESET_PASSWORD_EMAIL = 'RESET_PASSWORD_EMAIL';
export const COMPLETE_PASSWORD_RESET = 'COMPLETE_PASSWORD_RESET';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_ERROR = 'SET_USER_ERROR';
export const SET_USER_REQUEST = 'SET_USER_REQUEST';

export const SET_INIT_SLIDE = 'SET_INIT_SLIDE';
export const SET_NEXT_SLIDE = 'SET_NEXT_SLIDE';
export const SET_PREVIOUS_SLIDE = 'SET_PREVIOUS_SLIDE';

export const ADD_FILE = 'ADD_FILE';
export const REMOVE_FILE = 'REMOVE_FILE';
export const GET_CATEGORIES_FILES = 'GET_CATEGORIES_FILES';
export const SET_FILE_ERROR = 'SET_FILE_ERROR';
export const SET_UPLOAD_SUCCESS = 'SET_UPLOAD_SUCCESS';
export const GET_SINGLE_ART = 'GET_SINGLE_ART';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';

export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENT_REQUEST = 'GET_COMMENT_REQUEST';

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST';
export const EDIT_COMMENT_FAILURE = 'EDIT_COMMENT_FAILURE';
export const BOOKMARK_ART_REQUEST = 'BOOKMARK_ART_REQUEST';
export const BOOKMARK_ART_SUCCESS = 'BOOKMARK_ART_SUCCESS';
export const BOOKMARK_ART_FAILURE = 'BOOKMARK_ART_FAILURE';
export const DELETE_SINGLE_ART = 'DELETE_SINGLE_ART';
