export const RESET_PASSWORD_EMAIL = 'RESET_PASSWORD_EMAIL';
export const COMPLETE_PASSWORD_RESET = 'COMPLETE_PASSWORD_RESET';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_ERROR = 'SET_USER_ERROR';
export const SET_USER_REQUEST = 'SET_USER_REQUEST';

export const SET_INIT_SLIDE = 'SET_INIT_SLIDE';
export const SET_NEXT_SLIDE = 'SET_NEXT_SLIDE';
export const SET_PREVIOUS_SLIDE = 'SET_PREVIOUS_SLIDE';
