apiVersion: v1
kind: Pod
metadata:
  name: "node-es-container"
labels:
 component: ci
spec:
  # nodeSelector:
  #  beta.kubernetes.io/instance-type : n1-standard-1
  containers:
  - name: "node-es-container"
    image: node:erbium-slim
    resources:
      requests:
        cpu: "250m"
        memory: "300Mi"
      limits:
        cpu: "300m"
        memory: "500Mi"
    command:
    - cat
    tty: true
    env:
      - name: DOCKER_HOST
        value: tcp://0.0.0.0:2375

  - name: dind
    image: docker:19.03-dind
    resources:
      limits:
        cpu: "150m"
        memory: "500Mi"
    securityContext:
      privileged: true
    volumeMounts:
      - name: jenkins-disk
        mountPath: /var/lib/docker
  volumes:
  - name: jenkins-disk
    gcePersistentDisk:
      pdName: jenkins-disk
      fsType: ext4
