apiVersion: v1
kind: Pod
metadata:
  name: "jenkins-slave-container"
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
          weight: 100
  containers:
  - name: "node-es-container"
    image: node:carbon
    resources:
      requests:
        cpu: "200m"
        memory: "400Mi"
      limits:
        cpu: "300m"
        memory: "600Mi"
    command:
    - cat
    tty: true

  - name: dind
    image: docker:19.03-dind
    env:
      - name: DOCKER_HOST
        value: "tcp://docker-server:2375"
    securityContext:
      privileged: true

#  volumes:
#  - name: jenkins-disk
#    gcePersistentDisk:
#      pdName: jenkins-disk
#      fsType: ext4
#    - name: jenkins-disk
#      emptyDir: {}
#    - name: nfs
#      persistentVolumeClaim:
#        claimName: nfs
#    - name: jenkins-disk
#      hostPath:
#        path: /var/run/docker.sock
