apiVersion: v1
kind: Pod
metadata:
  name: "jenkins-slave-container"
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
          weight: 100
  containers:
  - name: "node-es-container"
    image: node:carbon
    resources:
      requests:
        cpu: "200m"
        memory: "400Mi"
      limits:
        cpu: "300m"
        memory: "600Mi"
    command:
    - cat
    tty: true
    env:
      - name: DOCKER_HOST
        value: tcp://0.0.0.0:2375

  - name: dind
    image: docker:19.03-dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: jenkins-disk-nfs
        mountPath: /var/lib/docker
#  volumes:
#  - name: jenkins-disk
#    gcePersistentDisk:
#      pdName: jenkins-disk
#      fsType: ext4
#  volumes:
#    - name: jenkins-disk
#      emptyDir: {}
  volumes:
    - name: jenkins-disk-nfs
      persistentVolumeClaim:
        claimName: data-nfs-server-provisioner-0

#  volumes:
#    - name: jenkins-disk
#      hostPath:
#        path: /var/run/docker.sock

