apiVersion: v1
kind: Pod
metadata:
  name: "nodeEs-container"
labels:
  component: ci
spec:
  containers:
  - name: "nodeEs-container"
    image: node:erbium-slim
    resources:
      requests:
        cpu: "250m"
        memory: "300Mi"
      limits:
        cpu: "300m"
        memory: "500Mi"
    command:
    - cat
    tty: true
    env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
  - name: dind
    image: docker:19.03-dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: jenkins-pv-storage
        mountPath: /var/lib/docker
  volumes:
  - name: jenkins-pv-storage
    persistentVolumeClaim:
        claimName: jenkins-pv-storage
