pipeline {
  agent{
    kubernetes {
      label 'merry-ah-frontend'
      defaultContainer 'jnlp'
      yamlFile 'jenkins/agent.yaml'
    }
  }

  stages {
    //  installing dependencies to use when running the pipeline
    stage('Install dependencies') {
      steps {
        container('node-es-container') {
          sh "chmod +x jenkins/npmcache.sh && ./jenkins/npmcache.sh" (label='NPM Cache')
//          sh "npm install" (label='NPM Install')
        }
      }
    }
    // Running parallel stages
    stage('Test and report') {
      parallel{
        // Running tests
        stage('Run tests') {
          steps {
            container('node-es-container') {
              sh "npm test --coverage"
            }
          }
        }

        stage('Npm build') {
          steps {
            container('node-es-container') {
              sh "npm run-script build"
            }
          }
        }

        // Building and pushing a docker image to GCR
        stage('Build Docker Image') {
          environment {
            IMG_TAG='\$(echo \$GIT_COMMIT | cut -c -7)'
          }

          steps {
            container('dind') {
              // sh "echo $GCLOUD_SERVICE_KEY | base64 -d > auth_key.json"
              // sh "gcloud auth activate-service-account --key-file auth_key.json"
              sh "docker --version"
              sh "docker build -f Dockerfile -t wombolo/merry-ah:$IMG_TAG ."
              sh "echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin"
              sh "docker push wombolo/merry-ah:$IMG_TAG"
            }
          }
        }
      }
    }
  }
}
