pipeline {
  agent{
    kubernetes {
      label 'merry-ah-frontend'
      defaultContainer 'jnlp'
      yamlFile 'jenkins/agent.yaml'
    }
  }

  stages {
    //  installing dependencies to use when running the pipeline
    stage('Install dependencies') {
      steps {
        container('node-es-container') {
          sh "npm install"
        }
      }
    }
    // Running parallel stages
    stage('Test and report') {
      parallel{
        // Running tests
        stage('Run tests') {
          steps {
            container('node-es-container') {
              sh "npm test --coverage"
            }
          }
        }

        stage('Build') {
          steps {
            container('node-es-container') {
              sh "npm build"
            }
          }
        }
      }
    }

    // Building and pushing a docker image to GCR
    stage('Build and push to GCR') {
      environment {
        IMG_TAG='\$(echo \$GIT_COMMIT | cut -c -7)'
      }

      steps {
        container('dind') {
          // sh "echo $GCLOUD_SERVICE_KEY | base64 -d > auth_key.json"
          // sh "gcloud auth activate-service-account --key-file auth_key.json"
          sh "docker --version"
          sh "docker build -f Dockerfile -t gcr.io/merry-ah:$IMG_TAG ."
          // sh "gcloud docker -- push gcr.io/merry-ah:$IMG_TAG"
        }
      }
    }
  }
}
